### ISSUE TITLE
fab gs.execute_setup returns 404s

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/debates#46]
But works for @jjelosua. Some sort of permissions issue?

**Comment by jjelosua** [comment]
When we deploy as an API executable we have to allow `anyone` instead of `anyone at NPR` to be able to use gmail credentials. 

There's a *caveat* people with `view` access to the script will be able to run the setup task so we should not have read access to anyone apart from the team on the script. IMO it should only allow those with `edit` access but life is hard sometimes...
